<div class="container">

    <form class="form-horizontal" method="POST" action="/mpd/show">
         <div class="form-group col-md-4">
          <label class="control-lable" for="sel1">Select Aircraft:</label>
            <?= $this->selectAircraft ?>
        </div>
        <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        </div>
    </form>
</div>