<div class="container">
    <section class="outlined-box">
      EDIT Version
    </section>
</div>

<script>
document.querySelector('button.delete-button').onclick = function(){
    swal({   title: "Are you sure that you want to delete this row?",   text: "",   type: "warning",   showCancelButton: true,   confirmButtonColor: "#DD6B55",   confirmButtonText: "Yes, delete it!",   closeOnConfirm: false }, function(){   doDelete();});
};
function doDelete(){
    var url = "/versions/deleterow/id/" + <?=$this->document_id?> + "/vid/" + <?=$this->document_version_id?> + "/rid/" + <?=$this->row_id?> ;
    window.location.assign(url);
    swal("Deleted!", "This row has been deleted.", "success");
}
</script>