<style>
.ngGrid , .gridView{
    height: 700px;
}
.gridContainer{
    padding: 20px;
}
.tool-tip:hover{
    cursor:help;
}
</style>

<div ng-app="versionApp" ng-controller="versionController">
<div class="container">
    <section class="outlined-box">
        <article>
            <strong><?= $this->document['name'] ?></strong>
            <span class="pull-right"><a href="" title="Download Excel"><i class="fa fa-download"></i></a></span>
        </article>
        <article>
        <div class="row">
            <div class="col-md-4">
                <ul>
                    <li>Revision Number: <?= $this->version['revision_num'] ?></li>
                    <li>Revision Date: <?= $this->version['revision_dt'] ?></li>
                    <li>Records: {{versionGrid.data.length}}</li>
                </ul>
                <?php if($this->version['comment']): ?>
                <p><strong>Comment</strong></p>
                <?= $this->version['comment'] ?>
                <?php endif; ?>
            </div>
            <div class="col-md-8">
                <strong>Source</strong>
                <?php if($this->sources): ?>

                <ul>
                    <?php foreach($this->sources as $source):?>
                        <li>
                            <a href="/document/download/id/<?=$source['id']?>"><?=$source['name']?></a> <?=$source['sheet_nm']?> <?=$source['updt_dtm']?> </li>
                    <?php endforeach; ?>
                </ul>
                <?php else: ?>
                    <p>No source documents found.</p>
                <?php endif; ?>

            </div>
        </div>
        </article>
    </section>
    </div>
    <div class="gridContainer">
        <div class="gridView" ui-grid="versionGrid" ui-grid-save-state ui-grid-resize-columns ui-grid-expandable-row class="grid mt20"></div>
    </div>

</div>

<link href="/angularjs/angular-ui-ui-grid.min.css" rel="stylesheet" type="text/css" >
<link rel=stylesheet href="/angularjs/angucomplete/angucomplete-alt.css">
<link rel=stylesheet href="/angularjs/angucomplete/CVK-angucomplete-alt.css">
<link href="/angularjs/angular-ui-ui-grid.min.css" rel="stylesheet" type="text/css" >

<script>
    var documentID = <?php echo $this->document_id ? $this->document_id : 0; ?>;
    var versionID = <?php echo $this->document_version_id ? $this->document_version_id : 0; ?>;
</script>
<script src="/angularjs/angular-1.5.3.min.js"></script>
<script src="/angularjs/ui-bootstrap-tpls-1.3.3.min.js"></script>
<script src="/angularjs/angular-ui-ui-grid.min.js"></script>
<script src="/angularjs/angucomplete/angucomplete-alt.js"></script>
<script src="/data-vault/common.js"></script>
<script src="/data-vault/versions/app.js"></script>
<script src="/data-vault/versions/controller.js"></script>
<script src="/data-vault/versions/load-save-factory.js"></script>
<script src="/data-vault/versions/loading-saving-directive.js"></script>