<script type="text/javascript">

    $(document).ready(function(){
        $('.add-paragraph-option').click(function() {
            var url = "/paragraph/createempty";
            var result = doAjax('post', url, {id:<?= isset($this->adParagraph[0]['ad_paragraph_id']) ? $this->adParagraph[0]['ad_paragraph_id'] : 0; ?>});
            if(result.newId !== ''){
                window.location.reload();
            }else{
            //
            }
        });
        
        
    });
</script>
<div class="container">
    <div id="toolbar">
        <?php if (Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'create'): ?>
        <h4>Add New Paragraph</h4>
        <?php else: ?>
        <h4>Edit Paragraph - <?= $this->adParagraph[0]['ad_paragraph_id']; ?></h4>
        <?php endif; ?>
    </div>
    <hr/>
    <div id="new_form_lgc">
        <form id="form_ad_paragraph" action="/paragraph/update" method="POST" class="form-horizontal mt20">
            <input type="hidden" id="ad_paragraph_id" name="ad_paragraph_id" value="<?= $this->adParagraph[0]['ad_paragraph_id']; ?>"/>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <label for="paragraph_name">Paragraph</label>
                    <input required type="text" class="form-control required" value="<?= $this->adParagraph[0]['paragraph_txt']; ?>" id="ad_para_name" name="ad_para_name" placeholder="Paragraph">
                </div>
            </div>
            <hr/>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <label for="if_condition">If</label>
                    <textarea required rows="4" class="form-control required" id="ad_para_if" name="ad_para_if" placeholder="If Condition"><?= $this->adParagraph[0]['if_txt']; ?></textarea>
                </div>
            </div>
            <hr/>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <label for="do_statement">Do</label>
                    <textarea required rows="4" class="form-control required" id="ad_para_do" name="ad_para_do" placeholder="Do Statement"><?= $this->adParagraph[0]['do_txt']; ?></textarea>
                </div>
            </div>
            <?php if (Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'edit'): ?>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-8">
                    <a class="add-paragraph-option" href="javascript:void();" title="Add Option"><i class="fa fa-plus-circle" style="color: #337ab7;">Add Option</i></a>
                    <table class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                        <thead>
                            <th>Option</th>
                            <th>Limit</th>
                            <th>From</th>
                            <th>Or Seq</th>
                            <th>Exception</th>
                            <th>Delete</th>
                        </thead>
                        <?php if ($this->paragraphOptions > 0): ?>
                        <tbody>
                            <?php foreach ($this->paragraphOptions as $option): ?>
                                <tr id="paragraph_option_0">
                                    <td><input name="option_txt_<?= $option['paragraph_option_id']; ?>" class="form-control required" type="text" value="<?php echo $option['option_txt']; ?>"/></td>
                                    <td><textarea name="limit_txt_<?= $option['paragraph_option_id']; ?>" class="form-control required"><?php echo $option['limit_txt']; ?></textarea></td>
                                    <td><textarea name="from_txt_<?= $option['paragraph_option_id']; ?>" class="form-control required"><?php echo $option['from_txt']; ?></textarea></td>
                                    <td><textarea name="or_txt_<?= $option['paragraph_option_id']; ?>" class="form-control required"><?php echo $option['or_txt']; ?></textarea></td>
                                    <td><textarea name="exception_txt_<?= $option['paragraph_option_id']; ?>" class="form-control required"><?php echo $option['exception_txt']; ?></textarea></td>
                                    <td><input type="checkbox" value="1" id="delete_<?= $option['paragraph_option_id']; ?>" name="delete_<?= $option['paragraph_option_id']; ?>"/></td>
                            </tr>
                        <?php endforeach; ?>
                            <?php else: ?>
                            
                            <?php endif ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <hr/>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <label for="notes_txt">Notes</label>
                    <textarea rows="4" class="form-control" id="ad_para_notes" name="ad_para_notes" placeholder="Notes"><?= $this->adParagraph[0]['notes_txt']; ?></textarea>
                </div>
            </div>
            <?php endif; ?>
            <div class="form-group">
                <div class="col-sm-offset-4 col-sm-6">
                    <?php if (Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'edit'): ?>
                    <input type='submit' id='button_1' name='submit' class="btn btn-primary" value='Save and Return'/>
                    <?php endif; ?>
                    <input type='submit' id='button_2' name='submit' class="btn btn-primary" value='Save'/>
                    <button class="btn btn-warning" onclick="history.go(-1)"> Return to Paragraph List</button>
                </div>
            </div>
        </form>
        <hr/>
    </div>
</div>