<script type="text/javascript">

    $(document).ready(function(){
        $('#ad-paragraph-actionable').click(function() {
            var url = "/paragraph/setactionable";
            var result = doAjax('post', url, {id:<?= isset($this->adParagraph[0]['ad_paragraph_id']) ? $this->adParagraph[0]['ad_paragraph_id'] : 0; ?>, actionable: <?= $this->adParagraph[0]['is_actionable']; ?>});
            if(result['message'] === 'ok'){
                window.location.reload();
            }else{
            //
            }
        });        
    });
</script><?php //var_dump($this->isActionable);exit; ?>
<div class="container">
    <div id="toolbar">
        <div class="row">
            <div class="col-sm-12">
                <div class="col-sm-6"><h3 style='color: #2aabd2;'><?= $this->adTxt; ?></h3></div>
                <div class="col-sm-6 text-right"><i title="Toggle actionable/Inactionable" id="ad-paragraph-actionable" class="<?= ($this->isActionable == 0) ? 'fa fa-eye-slash fa-5x' : 'fa fa-eye fa-5x';?>" aria-hidden="true"></i></div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="col-sm-4>">
                    <a class="btn btn-warning" href="/paragraph/index/id/<?= $_SESSION['adId']; ?>">Return to Paragraph</a> 
<!--                    <button class="btn btn-warning" onclick="history.go(-1)">Return to Paragraph</button>-->
                    <a class="btn btn-success" href="/paragraph/edit/id/<?= $this->adParagraph[0]['ad_paragraph_id']; ?>">Edit Paragraph</a>
        </div>
    </div>
    <hr/>
    <div id="new_form_lgc">
        <div id="form_ad_paragraph" class="form-horizontal mt20">
            <input type="hidden" id="ad_paragraph_id" name="ad_paragraph_id" value="<?= $this->adParagraph[0]['ad_paragraph_id']; ?>"/>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <label for="paragraph_name">Paragraph</label>
                    <input readonly type="text" class="form-control required" value="<?= $this->adParagraph[0]['paragraph_txt']; ?>" id="ad_para_name" name="ad_para_name" placeholder="Paragraph">
                </div>
            </div>
            <hr/>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <label for="if_condition">If</label>
                    <textarea readonly rows="4" class="form-control required" id="ad_para_if" name="ad_para_if" placeholder="If Condition"><?= $this->adParagraph[0]['if_txt']; ?></textarea>
                </div>
            </div>
            <hr/>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <label for="do_statement">Do</label>
                    <textarea readonly rows="4" class="form-control required" id="ad_para_do" name="ad_para_do" placeholder="Do Statement"><?= $this->adParagraph[0]['do_txt']; ?></textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-8">
                    <table class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                        <thead>
                            <th>Option</th>
                            <th>Limit</th>
                            <th>From</th>
                            <th>Or Seq</th>
                            <th>Exception</th>
                        </thead>
                        <?php if ($this->paragraphOptions > 0): ?>
                        <tbody>
                            <?php foreach ($this->paragraphOptions as $option): ?>
                                <tr id="paragraph_option_0">
                                    <td><input readonly name="option_txt_<?= $option['paragraph_option_id']; ?>" class="form-control required" type="text" value="<?php echo $option['option_txt']; ?>"/></td>
                                    <td><textarea readonly name="limit_txt_<?= $option['paragraph_option_id']; ?>" class="form-control required"><?php echo $option['limit_txt']; ?></textarea></td>
                                    <td><textarea readonly name="from_txt_<?= $option['paragraph_option_id']; ?>" class="form-control required"><?php echo $option['from_txt']; ?></textarea></td>
                                    <td><textarea readonly name="or_txt_<?= $option['paragraph_option_id']; ?>" class="form-control required"><?php echo $option['or_txt']; ?></textarea></td>
                                    <td><textarea readonly name="exception_txt_<?= $option['paragraph_option_id']; ?>" class="form-control required"><?php echo $option['exception_txt']; ?></textarea></td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                        <?php endif; ?>
                    </table>
                </div>
            </div>
            <hr/>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <label for="notes_txt">Notes</label>
                    <textarea readonly rows="4" class="form-control required" id="ad_para_notes" name="ad_para_notes" placeholder="Notes"><?= $this->adParagraph[0]['notes_txt']; ?></textarea>
                </div>
            </div>
        </div>
        <hr/>
    </div>
</div>