<!DOCTYPE html>
<html lang="en">
  <head>
      <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
      <?php echo (isset($this->metaCustom))?$this->metaCustom:""; ?>
      <?php echo $this->headTitle(); ?>
      <?php echo $this->headLink(); ?>
      <?php echo $this->headStyle(); ?>
      <?php echo $this->headScript(); ?>
      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!--[if lt IE 9]>
      <script src="/js/html5shiv.js"></script>
      <script src="/js/respond.min.js"></script>
      <![endif]-->

  </head>
<body>
    <?php echo $this->render('header.phtml');?>
    <?php echo $this->layout()->content; ?>
    <?php echo $this->render('footer.phtml');?>
<script type="text/javascript" src="http://assets.freshdesk.com/widget/freshwidget.js"></script>
<script type="text/javascript" src="https://s3.amazonaws.com/assets.freshdesk.com/widget/freshwidget.js"></script>
<script type="text/javascript">
  FreshWidget.init("", {"queryString": "&widgetType=popup", "utf8": "✓", "widgetType": "popup", "buttonType": "text", "buttonText": "Support", "buttonColor": "black", "buttonBg": "#8cdcff", "alignment": "2", "offset": "50px", "formHeight": "500px", "url": "https://cavokgroup.freshdesk.com"} );
  </script>
</body>
</html>
